[0m16:38:17.296277 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024088917A40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024088917EC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024088917AA0>]}


============================== 16:38:17.300782 | b314f02c-7344-428e-a613-b6b3ce4c5732 ==============================
[0m16:38:17.300782 [info ] [MainThread]: Running with dbt=1.9.4
[0m16:38:17.300782 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Avi\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt init my_dbt_project', 'send_anonymous_usage_stats': 'True'}
[0m16:38:17.314303 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'WindowsPath'.. Dictionary: {'dir': WindowsPath('C:/Users/Avi/.dbt')}
[0m16:38:17.315303 [info ] [MainThread]: Creating dbt configuration folder at 
[0m16:38:17.316304 [debug] [MainThread]: Starter project path: C:\Users\Avi\Desktop\ft_poc\bi-dwh-poc\bi-dwh-poc\venv\Lib\site-packages\dbt\include\starter_project
[0m16:38:17.354022 [info ] [MainThread]: 
Your new dbt project "my_dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m16:38:17.354022 [info ] [MainThread]: Setting up your profile.
[0m16:42:44.369705 [info ] [MainThread]: Profile my_dbt_project written to C:\Users\Avi\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m16:42:44.370714 [debug] [MainThread]: Command `dbt init` succeeded at 16:42:44.370714 after 267.30 seconds
[0m16:42:44.370714 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002408585CE00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024088329880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000240885D2960>]}
[0m16:42:44.371712 [debug] [MainThread]: Flushing usage events
[0m16:42:45.073777 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:44:23.050247 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D725C3CBF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D728CF7E90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D728CF7D10>]}


============================== 16:44:23.056762 | b8abfdb3-b2eb-413c-994d-5f6c95d02440 ==============================
[0m16:44:23.056762 [info ] [MainThread]: Running with dbt=1.9.4
[0m16:44:23.057762 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Avi\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m16:44:23.075968 [info ] [MainThread]: dbt version: 1.9.4
[0m16:44:23.075968 [info ] [MainThread]: python version: 3.12.10
[0m16:44:23.077210 [info ] [MainThread]: python path: C:\Users\Avi\Desktop\ft_poc\bi-dwh-poc\bi-dwh-poc\venv\Scripts\python.exe
[0m16:44:23.077210 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m16:44:23.122326 [info ] [MainThread]: Using profiles dir at C:\Users\Avi\.dbt
[0m16:44:23.123327 [info ] [MainThread]: Using profiles.yml file at C:\Users\Avi\.dbt\profiles.yml
[0m16:44:23.124324 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Avi\Desktop\ft_poc\bi-dwh-poc\bi-dwh-poc\dbt_project.yml
[0m16:44:23.124324 [info ] [MainThread]: adapter type: postgres
[0m16:44:23.125325 [info ] [MainThread]: adapter version: 1.9.0
[0m16:44:23.126328 [info ] [MainThread]: Configuration:
[0m16:44:23.126328 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m16:44:23.126328 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m16:44:23.127327 [info ] [MainThread]: Required dependencies:
[0m16:44:23.127847 [debug] [MainThread]: Executing "git --help"
[0m16:44:23.209935 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m16:44:23.209935 [debug] [MainThread]: STDERR: "b''"
[0m16:44:23.210937 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m16:44:23.210937 [info ] [MainThread]: Connection:
[0m16:44:23.211940 [info ] [MainThread]:   host: 
[0m16:44:23.211940 [info ] [MainThread]:   port: 5432
[0m16:44:23.213034 [info ] [MainThread]:   user: 
[0m16:44:23.213034 [info ] [MainThread]:   database: 
[0m16:44:23.213034 [info ] [MainThread]:   schema: 
[0m16:44:23.214032 [info ] [MainThread]:   connect_timeout: 10
[0m16:44:23.214032 [info ] [MainThread]:   role: None
[0m16:44:23.214032 [info ] [MainThread]:   search_path: None
[0m16:44:23.215030 [info ] [MainThread]:   keepalives_idle: 0
[0m16:44:23.215030 [info ] [MainThread]:   sslmode: None
[0m16:44:23.216036 [info ] [MainThread]:   sslcert: None
[0m16:44:23.216036 [info ] [MainThread]:   sslkey: None
[0m16:44:23.217036 [info ] [MainThread]:   sslrootcert: None
[0m16:44:23.217036 [info ] [MainThread]:   application_name: dbt
[0m16:44:23.218033 [info ] [MainThread]:   retries: 1
[0m16:44:23.219037 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m16:44:23.404365 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m16:44:23.536984 [debug] [MainThread]: Using postgres connection "debug"
[0m16:44:23.537644 [debug] [MainThread]: On debug: select 1 as id
[0m16:44:23.538180 [debug] [MainThread]: Opening a new connection, currently in state init
[0m16:44:23.541942 [debug] [MainThread]: Postgres adapter: Got a retryable error when attempting to open a postgres connection.
1 attempts remaining. Retrying in 0 seconds.
Error:
could not translate host name "" to address: No such host is known. 

[0m16:44:23.542942 [debug] [MainThread]: Postgres adapter: Error running SQL: select 1 as id
[0m16:44:23.542942 [debug] [MainThread]: Postgres adapter: Rolling back transaction.
[0m16:44:23.542942 [debug] [MainThread]: On debug: No close available on handle
[0m16:44:23.543942 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m16:44:23.543942 [info ] [MainThread]: [31m2 checks failed:[0m
[0m16:44:23.544947 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\Avi\Desktop\ft_poc\bi-dwh-poc\bi-dwh-poc\dbt_project.yml> not found

[0m16:44:23.546264 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  could not translate host name "" to address: No such host is known. 
  

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m16:44:23.547938 [debug] [MainThread]: Command `dbt debug` failed at 16:44:23.547886 after 0.80 seconds
[0m16:44:23.548503 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m16:44:23.549012 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D726377C50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D728D5A1E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D7287303E0>]}
[0m16:44:23.549012 [debug] [MainThread]: Flushing usage events
[0m16:44:24.270375 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:46:36.691069 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020309334800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002030C3841A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002030C3851F0>]}


============================== 13:46:36.698546 | e6ccb2ca-ca70-47e7-9165-da20e424c4cc ==============================
[0m13:46:36.698546 [info ] [MainThread]: Running with dbt=1.9.4
[0m13:46:36.698546 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\Avi\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m13:46:36.698546 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Avi\Desktop\ft_poc\bi-dwh-poc\bi-dwh-poc\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:46:36.700052 [debug] [MainThread]: Command `dbt run` failed at 13:46:36.700052 after 0.24 seconds
[0m13:46:36.701058 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002030BD583B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002030C386C90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002030C385220>]}
[0m13:46:36.701058 [debug] [MainThread]: Flushing usage events
[0m13:46:37.336429 [debug] [MainThread]: An error was encountered while trying to flush usage events
